Use the user id instead of user name so k8s can pick it up as non-root (#891)
# Problem

`USER gateway` is not enough for k8s and it will still throw:

```
Error: container has runAsNonRoot and image has non-numeric user (gateway), cannot verify user is non-root (pod: "...", container: account-service-api)
```

# Solution

Switch to `USER 1001` the hard coded user id